Repository WordPress/openverse, pull requests merged in 2021-09, with the labels that each got.

#62 Improve documentation for workflows
  .github/GITHUB.md
  .github/sync.yml
  .github/workflows/label_sync.yml
  .github/workflows/new_issues.yml
  .github/workflows/new_prs.yml
  .github/workflows/pr_label_check.yml
  .github/workflows/project_automation.yml
  .github/workflows/sync_meta.yml
Labels: ✨ goal: improvement, 📄 aspect: text

#61 Ensure the presence of required label groups on PR
  .github/GITHUB.md
  .github/sync.yml
  .github/workflows/label_sync.yml
  .github/workflows/new_issues.yml
  .github/workflows/new_prs.yml
  .github/workflows/pr_label_check.yml
  .github/workflows/project_automation.yml
  .github/workflows/sync_meta.yml
Labels: 🌟 goal: addition, 🤖 aspect: dx

#63 Add a label for a11y
  .github/workflows/pr_label_check.yml
  data/labels.yml
Labels: 🌟 goal: addition, 🤖 aspect: dx

#66 Update README.md
  README.md
Labels: 🟩 priority: low, 📄 aspect: text, 🧰 goal: internal improvement

#69 Update PR automation for forks
  .github/workflows/new_prs.yml
Labels: 🛠 goal: fix, 🤖 aspect: dx

#76 Add a trailing newline to the workflow
  .github/workflows/pr_label_check.yml
Labels: 🛠 goal: fix, 🤖 aspect: dx

#77 Simpler and clearer pull request template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: 🟩 priority: low, 🤖 aspect: dx, 🧰 goal: internal improvement

#80 Correct spelling
  README.md
Labels: 🛠 goal: fix, 📄 aspect: text
