Repository WordPress/openverse, pull requests merged in 2021-12, with the labels that each got.

#101 Add linting and pre-commit hooks for Python code
  .flake8
  .github/GITHUB.md
  .gitignore
  .pre-commit-config.yaml
  README.md
  data/github.yml
  js/.gitignore
  justfile
  python/.gitignore
  python/Pipfile
  python/Pipfile.lock
  python/archive_column.py
  python/issues_with_prs.py
  python/models/label.py
  python/models/label_group.py
  python/shared/data.py
  python/shared/github.py
  python/shared/project.py
  python/sync_labels.py
Labels: 🟨 priority: medium, 🤖 aspect: dx, 🧰 goal: internal improvement

#90 Added formatting rules to js folder
  .pre-commit-config.yaml
  js/.eslintrc.js
  js/.prettierrc
  js/prettier.config.js
  js/src/last_week_tonight.js
  js/src/migrate_issues.js
  js/src/utils.js
  js/src/weekly_report.js
Labels: 🟨 priority: medium, 🤖 aspect: dx, 🧰 goal: internal improvement

#115 Send Slack ping when PR is marked ready for review
  .github/workflows/pr_ping.yml
Labels: 🟩 priority: low, 🌟 goal: addition, 🤖 aspect: dx

#116 Add priority label to sync PRs
  .github/workflows/sync_meta.yml
Labels: 🟩 priority: low, 🤖 aspect: dx, 🧰 goal: internal improvement

#121 Add a workflow for a notification on new discussions
  .github/GITHUB.md
  .github/workflows/discussion_ping.yml
Labels: 🟩 priority: low, ✨ goal: improvement, 🤖 aspect: dx

#127 Readme: fix link to Openverse P2
  README.md
Labels: 🟥 priority: critical, 🛠 goal: fix, 📄 aspect: text

#128 Add technology labels
  data/labels.yml
Labels: 🟩 priority: low, 🌟 goal: addition, 🤖 aspect: dx

#129 Add PR ping functionality to the infra repo
  .github/sync.yml
Labels: 🟩 priority: low, ✨ goal: improvement, 🤖 aspect: dx

#130 Fix issues with the PR project automation
  .github/workflows/pr_project_automation.yml
Labels: 🟨 priority: medium, 🛠 goal: fix, 🤖 aspect: dx

#131 Lint YAML files using Prettier
  .github/workflows/discussion_ping.yml
  .github/workflows/label_sync.yml
  .github/workflows/new_issues.yml
  .github/workflows/new_prs.yml
  .github/workflows/pr_label_check.yml
  .github/workflows/pr_ping.yml
  .github/workflows/pr_project_automation.yml
  .github/workflows/project_automation.yml
  .github/workflows/sync_meta.yml
  .github/workflows/weekly_updates.yml
  .pre-commit-config.yaml
  data/labels.yml
Labels: 🟩 priority: low, 🤖 aspect: dx, 🧰 goal: internal improvement
