Repository WordPress/openverse, pull requests merged in 2022-03, with the labels that each got.

#174 RFC: Migration from Vuex to Pinia in the front-end
  rfcs/20220223-convert_the_store_from_vuex_to_pinia.md
Labels: 🟨 priority: medium, 🌟 goal: addition, 💻 aspect: code

#180 Create a workflow to label a PR based on its linked issues
  .github/sync.yml
  .github/workflows/label_new_pr.yml
  .github/workflows/label_pr.yml
  .github/workflows/pr_label_check.yml
  python/Pipfile
  python/Pipfile.lock
  python/label_pr.py
Labels: 🟨 priority: medium, 🌟 goal: addition, 🤖 aspect: dx

#185 Prevent PR labeller from overwriting labels on labelled PRs
  python/label_pr.py
Labels: 🟥 priority: critical, 🛠 goal: fix, 💻 aspect: code

#188 Update Python workflows to run on Python 3.10
  .github/workflows/label_pr.yml
  .github/workflows/label_sync.yml
  .github/workflows/pr_project_automation.yml
  .github/workflows/project_automation.yml
Labels: 🟩 priority: low, 💻 aspect: code, 🧰 goal: internal improvement

#189 Update Pipenv files for Python 3.10
  python/Pipfile
  python/Pipfile.lock
Labels: 🟥 priority: critical, 🛠 goal: fix, 💻 aspect: code

#191 Label PRs by contributors
  .github/workflows/label_new_pr.yml
Labels: 🟥 priority: critical, 🛠 goal: fix, 🤖 aspect: dx

#171 RFC: 3D Model Support
  rfcs/20220221-3d_model_support.md
Labels: 🟨 priority: medium, 🌟 goal: addition, 🕹 aspect: interface, 💬 talk: discussion

#198 Update bug_report.md to remove default priority label
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: 🚦 status: awaiting triage

#202 Update feature_request.md label template to remove priority and aspect
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: 🚦 status: awaiting triage

#204 Add discussion template
  .github/ISSUE_TEMPLATE/discussion.md
Labels: 🟩 priority: low, ✨ goal: improvement, 📄 aspect: text

#201 Move automations into their own directory; update README
  .github/workflows/label_pr.yml
  .github/workflows/label_sync.yml
  .github/workflows/pr_project_automation.yml
  .github/workflows/project_automation.yml
  .github/workflows/weekly_updates.yml
  .pre-commit-config.yaml
  README.md
  automations/.flake8
  automations/README.md
  automations/data/github.yml
  automations/data/labels.yml
  automations/js/.eslintrc.js
  automations/js/.gitignore
  automations/js/package-lock.json
  automations/js/package.json
  automations/js/prettier.config.js
  automations/js/src/last_week_tonight.js
  automations/js/src/migrate_issues.js
  automations/js/src/utils.js
  automations/js/src/weekly_report.js
  automations/python/.gitignore
  automations/python/Pipfile
  automations/python/Pipfile.lock
  automations/python/README.md
  automations/python/archive_column.py
  automations/python/issues_with_prs.py
  automations/python/label_pr.py
  automations/python/models/__init__.py
  automations/python/models/label.py
  automations/python/models/label_group.py
  automations/python/shared/__init__.py
  automations/python/shared/data.py
  automations/python/shared/github.py
  automations/python/shared/log.py
  automations/python/shared/project.py
  automations/python/sync_labels.py
  justfile
Labels: 🟩 priority: low, ✨ goal: improvement, 💻 aspect: code

#199 Remove access token usage
  .github/workflows/label_new_pr.yml
  .github/workflows/label_pr.yml
  .github/workflows/label_sync.yml
  .github/workflows/new_issues.yml
  .github/workflows/new_prs.yml
  .github/workflows/pr_project_automation.yml
  .github/workflows/project_automation.yml
  .github/workflows/sync_meta.yml
  .github/workflows/weekly_updates.yml
Labels: 🟨 priority: medium, ✨ goal: improvement, 💻 aspect: code
