Repository WordPress/openverse, pull requests merged in 2022-06, with the labels that each got.

#251 Update weekly_report.js to remove old auth token
  automations/js/src/weekly_report.js
Labels: 🚦 status: awaiting triage

#248 Add mechanism to access pages in private repos
  automations/python/Pipfile
  automations/python/Pipfile.lock
  automations/python/label_pr.py
Labels: 🟩 priority: low, 🌟 goal: addition, 💻 aspect: code

#259 Add GitHub secrets to label PR workflow env
  .github/workflows/label_pr.yml
Labels: 🟧 priority: high, 🛠 goal: fix, 🤖 aspect: dx

#266 Adding a link to make design handbook
  README.md
Labels: 🚦 status: awaiting triage

#261 Update good first issue link in CONTRIBUTING.md
  CONTRIBUTING.md
  README.md
Labels: 🟩 priority: low, ✨ goal: improvement, 📄 aspect: text
