Repository WordPress/openverse, pull requests merged in 2022-02, with the labels that each got.

#145 Add CSS technology label
  data/labels.yml
Labels: 🟩 priority: low, ✨ goal: improvement, 🤖 aspect: dx

#164 RFC: Introduce UI state cookie
  rfcs/20220218-introduce_ui_state_cookie_to_frontend.md
Labels: 🟩 priority: low, ✨ goal: improvement, 🕹 aspect: interface

#163 Add RFC README.md
  rfcs/README.md
Labels: 🟨 priority: medium, 📄 aspect: text, 🧰 goal: internal improvement

#172 Add minimum wait period to RFCs
  rfcs/README.md
Labels: 🟨 priority: medium, ✨ goal: improvement, 📄 aspect: text

#173 Add new tech labels for Bash and TypeScript
  data/labels.yml
Labels: 🟩 priority: low, 🌟 goal: addition, 🤖 aspect: dx

#165 RFC: Visual regression testing
  rfcs/20220217-visual_regression_testing.md
Labels: 🟨 priority: medium, 🤖 aspect: dx, 🧰 goal: internal improvement
