Repository WordPress/openverse, pull requests merged in 2022-10, with the labels that each got.

#310 Add concurrency settings for workflow
  .github/workflows/actionlint.yml
  .github/workflows/lint.yml
Labels: 🚦 status: awaiting triage

#309 Update scraping logic to keep up with GitHub UI
  automations/python/label_pr.py
Labels: 🟨 priority: medium, 🛠 goal: fix, 💻 aspect: code

#301 Add dead link scripts
  dead_links/Pipfile
  dead_links/Pipfile.lock
  dead_links/dead_link_tally.py
Labels: 🟨 priority: medium, 🌟 goal: addition, 💻 aspect: code

#318 Fix subscribe-to-label config file name
  .github/subscribe-to-label.json
Labels: 🟧 priority: high, 🛠 goal: fix, 🤖 aspect: dx

#319 Update synced files list to new subscribe-to-json filename
  .github/sync.yml
Labels: 🟧 priority: high, 🛠 goal: fix, 🤖 aspect: dx

#322 Added notes by @rwidom in CONTRIBUTING.md
  CONTRIBUTING.md
Labels: 🟩 priority: low, ✨ goal: improvement, 📄 aspect: text
