Repository WordPress/openverse, pull requests merged in 2022-11, with the labels that each got.

#328 Fix the week in Openverse posts
  .github/workflows/weekly_updates.yml
Labels: 🟨 priority: medium, 🛠 goal: fix, 💻 aspect: code

#330 Unify pre-commit config across repos
  .flake8
  .github/sync.yml
  .pre-commit-config.yaml
  automations/python/label_pr.py
  automations/python/shared/data.py
  automations/python/shared/github.py
Labels: 🟩 priority: low, ✨ goal: improvement, 🤖 aspect: dx

#331 Use `pnpm` in Just recipe to install JS deps
  justfile
Labels: 🟩 priority: low, 🤖 aspect: dx, 🧰 goal: internal improvement

#332 Expand Prettier to eliminate pretty-format-json
  .github/subscribe-to-label.json
  .pre-commit-config.yaml
  automations/js/src/weekly_report.js
  load_testing/k6/main.js
  load_testing/k6/search.js
  load_testing/k6/utils.js
  pnpm-lock.yaml
  prettier.config.js
  renovate.json
Labels: 🟧 priority: high, 🛠 goal: fix, 💻 aspect: code
