Repository WordPress/openverse, pull requests merged in 2022-07, with the labels that each got.

#273 Switch to proper host for macos detection
  load_testing/justfile
Labels: 🟩 priority: low, 🛠 goal: fix, 💻 aspect: code

#274 Add sentry bug issue template
  .github/ISSUE_TEMPLATE/sentry_bug.md
Labels: 🟨 priority: medium, 🛠 goal: fix, 🤖 aspect: dx

#280 Remove load testing container after run
  load_testing/justfile
Labels: 🟩 priority: low, ✨ goal: improvement, 🤖 aspect: dx

#279 Add k6 load testing script
  automations/js/package-lock.json
  automations/js/package.json
  load_testing/Dockerfile
  load_testing/justfile
  load_testing/k6/main.js
  load_testing/k6/search.js
  load_testing/k6/utils.js
Labels: 🟥 priority: critical, 💻 aspect: code, 🧰 goal: internal improvement

#282 Switch to pnpm
  .gitignore
  automations/js/.gitignore
  automations/js/package-lock.json
  package.json
  pnpm-lock.yaml
Labels: 🟩 priority: low, 🤖 aspect: dx, 🧰 goal: internal improvement
