Repository WordPress/openverse, pull requests merged in 2022-09, with the labels that each got.

#302 Add space to change `[]` into checkboxes
  .github/ISSUE_TEMPLATE/discussion.md
Labels: 🟩 priority: low, 🛠 goal: fix, 📄 aspect: text

#303 Add sentry label to issue template
  .github/ISSUE_TEMPLATE/sentry_bug.md
Labels: 🟩 priority: low, 📄 aspect: text, 🧰 goal: internal improvement

#304 Remove trailing comma, fix sentry issue template
  .github/ISSUE_TEMPLATE/sentry_bug.md
Labels: 🟨 priority: medium, 🛠 goal: fix, 📄 aspect: text

#305 Add more possible contributions to CONTRIBUTING.md
  CONTRIBUTING.md
Labels: 🟩 priority: low, ✨ goal: improvement, 📄 aspect: text
