Repository WordPress/openverse, pull requests merged in 2022-12, with the labels that each got.

#346 Removed "Implementation/Resolution" section from issue templates (#329)
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: 🟩 priority: low, ✨ goal: improvement, 🤖 aspect: dx

#347 Change the label checker action
  .github/workflows/pr_label_check.yml
Labels: 🚦 status: awaiting triage

#349 Auto-format markdown; switch to double quotes for JS
  .github/GITHUB.md
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/discussion.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE.md
  .pre-commit-config.yaml
  .pre-commit-config.yaml.jinja
  CONTRIBUTING.md
  README.md
  automations/README.md
  automations/python/README.md
  brand/README.md
  justfile
  load_testing/README.md
  load_testing/k6/main.js
  load_testing/k6/search.js
  load_testing/k6/utils.js
  prettier.config.js
  prettier.config.js.jinja
  rfcs/20220217-visual_regression_testing.md
  rfcs/20220218-introduce_ui_state_cookie_to_frontend.md
  rfcs/20220221-3d_model_support.md
  rfcs/20220223-convert_the_store_from_vuex_to_pinia.md
  rfcs/20220307-monitoring_across_the_stack.md
  rfcs/20220309-feature_flags.md
  rfcs/README.md
Labels: 🟩 priority: low, ✨ goal: improvement, 🤖 aspect: dx

#350 Add repo token to label check workflow
  .github/workflows/pr_label_check.yml
Labels: 🟧 priority: high, 🛠 goal: fix, 🤖 aspect: dx

#354 Update lint configs and templates to use double quotes
  .pre-commit-config.frontend.yaml.jinja
  prettier.config.frontend.js.jinja
  prettier.config.js
  prettier.config.js.jinja
Labels: 🟩 priority: low, 🛠 goal: fix, 💻 aspect: code
