Repository WordPress/openverse, pull requests merged in 2022-04, with the labels that each got.

#211 Use PAT for repository dispatch
  .github/workflows/label_new_pr.yml
Labels: 🟥 priority: critical, 🛠 goal: fix, 🤖 aspect: dx

#213 Adding Sentry Label for issues originating from a Sentry report
  automations/data/labels.yml
Labels: 🟩 priority: low, ✨ goal: improvement, 🤖 aspect: dx

#193 RFC: Monitoring across the stack
  .gitignore
  rfcs/20220307-monitoring_across_the_stack.md
Labels: 🟧 priority: high, 🌟 goal: addition, 📄 aspect: text, 💬 talk: discussion

#219 Fix linting error
  rfcs/20220307-monitoring_across_the_stack.md
Labels: 🟩 priority: low, 🤖 aspect: dx, 🧰 goal: internal improvement

#220 Add `aspect: design` label
  automations/data/labels.yml
Labels: 🚦 status: awaiting triage

#222 Fix broken label sync action
  .github/workflows/label_sync.yml
  automations/data/labels.yml
Labels: 🟨 priority: medium, 🛠 goal: fix, 🤖 aspect: dx
