Repository WordPress/openverse, pull requests merged in 2022-05, with the labels that each got.

#186 Add an RFC for working with feature flags
  rfcs/20220309-feature_flags.md
Labels: 🟩 priority: low, ✨ goal: improvement, 💻 aspect: code

#227 Update CODEOWNERS to maintainers team
  .github/CODEOWNERS
Labels: 🟨 priority: medium, 🤖 aspect: dx, 🧰 goal: internal improvement

#225 Change priority label wording from "fixed" to "addressed"
  automations/data/labels.yml
Labels: 🟩 priority: low, 📄 aspect: text, 🧰 goal: internal improvement

#241 Change a 'Helpful links for new contributors' url of the readme.md file
  README.md
Labels: 🟩 priority: low, ✨ goal: improvement, 📄 aspect: text
