Repository WordPress/openverse, pull requests merged in 2023-02, with the labels that each got.

#371 Add additional rules to ignore for pydocstyle
  .pre-commit-config.yaml
  templates/.pre-commit-config.yaml.jinja
Labels: 🟧 priority: high, 🛠 goal: fix, 🤖 aspect: dx

#372 Add remake to eslint_exclude
  templates/.pre-commit-config.frontend.yaml.jinja
Labels: 🟨 priority: medium, 🛠 goal: fix, 🤖 aspect: dx

#375 fix: Remove references to the unmaintained browser extension
  .github/sync.yml
  README.md
  automations/data/github.yml
Labels: 🟧 priority: high, 💻 aspect: code, 🧰 goal: internal improvement

#373 Addition of "waiting for triage" label in case label_pr.yml fails
  .github/workflows/label_new_pr.yml
Labels: 🟩 priority: low, 🛠 goal: fix, 🤖 aspect: dx

#376 Match frontend linting dependency versions to frontend/pull/2121
  templates/.pre-commit-config.frontend.yaml.jinja
Labels: 🟨 priority: medium, 💻 aspect: code, 🧰 goal: internal improvement

#395 Change authentication token
  .github/workflows/pr_project_automation.yml
Labels: 🟨 priority: medium, 🛠 goal: fix, 🤖 aspect: dx

#401 Restore the functionality of the weekly Make post
  .github/workflows/weekly_updates.yml
  package.json
  pnpm-lock.yaml
Labels: 🟩 priority: low, 🛠 goal: fix, 💻 aspect: code

#405 Fix authenticated logins for the label PR action
  automations/python/label_pr.py
  docs/projects/README.md
Labels: 🟧 priority: high, 🛠 goal: fix, 🤖 aspect: dx

#406 Remove front matter from project proposal template
  .github/PULL_REQUEST_TEMPLATE/project_proposal.md
Labels: 🟧 priority: high, 🛠 goal: fix, 📄 aspect: text

#407 Change 'Reverted' to 'Rollback' in project docs
  docs/projects/README.md
Labels: 🟩 priority: low, 🛠 goal: fix, 📄 aspect: text

#396 Fix project automation logic around closed PRs
  .github/workflows/project_automation.yml
  automations/python/issues_with_prs.py
  automations/python/shared/github.py
Labels: 🟨 priority: medium, 🛠 goal: fix, 💻 aspect: code

#418 Update sync to account changes to PR template path
  .github/sync.yml
  justfile
  templates/pull_request_template.catalog.md.jinja
  templates/pull_request_template.md.jinja
Labels: 🟨 priority: medium, 🛠 goal: fix, 💻 aspect: code

#336 RFC: Monorepo
  rfcs/20221124-monorepo.md
Labels: 🟨 priority: medium, ✨ goal: improvement, 💻 aspect: code, 🔍 ov: meta

#441 Improve the monorepo workflow
  .github/workflows/ci_cd.yml
  .github/workflows/generate_pot.yml
  .github/workflows/sync_meta.yml
  api/justfile
  automations/js/justfile
  automations/python/justfile
  frontend/justfile
  ingestion_server/justfile
  justfile
  nginx/justfile
Labels: 🟨 priority: medium, ✨ goal: improvement, 💻 aspect: code

#761 Wrap README image in an openverse.org link
  README.md
Labels: 🟩 priority: low, ✨ goal: improvement, 🤖 aspect: dx

#443 Update documentation system to cover all projects
  .github/actions/build-docs/action.yml
  .github/workflows/ci_cd.yml
  api/Pipfile
  api/Pipfile.lock
  api/docs/_static/_css/brand.css
  api/docs/_templates/sidebar/brand.html
  api/docs/conf.py
  api/docs/guides/index.md
  api/docs/guides/quickstart.md
  api/docs/index.md
  api/docs/reference/api/constants.rst
  api/docs/reference/api/controllers.rst
  api/docs/reference/api/docs.rst
  api/docs/reference/api/examples.rst
  api/docs/reference/api/index.rst
  api/docs/reference/api/models.rst
  api/docs/reference/api/serializers.rst
  api/docs/reference/api/utils.rst
  api/docs/reference/api/views.rst
  api/docs/reference/index.rst
  api/docs/reference/urls.rst
  api/justfile
  documentation/.gitignore
  documentation/Pipfile
  documentation/Pipfile.lock
  documentation/_static/api_redoc.png
  documentation/_static/logo_dark.svg
  documentation/_static/logo_light.svg
  documentation/_static/publish_action_example.png
  documentation/conf.py
  documentation/guides/deploy.md
  documentation/guides/document.md
  documentation/guides/https.md
  documentation/guides/index.md
  documentation/guides/logging.md
  documentation/guides/publish.md
  documentation/guides/quickstart.md
  documentation/guides/run.md
  documentation/guides/test.md
  documentation/guides/zero-downtime-database-management.md
  documentation/index.md
  documentation/justfile
  documentation/reference/api/authentication_and_throttling.md
  documentation/reference/api/index.md
  documentation/reference/index.md
  documentation/reference/search_algorithm.md
  documentation/terms_of_service.md
  justfile
Labels: 🟧 priority: high, 🌟 goal: addition, 📄 aspect: text

#763 Remove the API and Frontend repos from project automation
  automations/data/github.yml
Labels: 🟧 priority: high, 🛠 goal: fix, 🤖 aspect: dx

#765 Don't move issues back & forth in project, reduce API calls for project automation
  automations/python/issues_with_prs.py
Labels: 🟥 priority: critical, 🛠 goal: fix, 🤖 aspect: dx

#446 Use a hack to compile the frontend container with workspaces
  .github/workflows/ci_cd.yml
  .github/workflows/generate_pot.yml
  .npmrc
  .pnpmfile.cjs
  .pre-commit-config.yaml
  frontend/.gitignore
  frontend/Dockerfile
  frontend/bin/playwright.sh
  frontend/justfile
  frontend/package.json
  frontend/pnpm-lock.yaml
  justfile
  pnpm-lock.yaml
  pnpm-workspace.yaml
  templates/.pre-commit-config.local.yaml.jinja
  templates/.pre-commit-config.yaml.jinja
Labels: 🟨 priority: medium, ✨ goal: improvement, 💻 aspect: code

#766 Move docs to `documentation/`, reduce duplication and update content
  CONTRIBUTING.md
  README.md
  api/justfile
  api/meta_docs/CONTRIBUTING.md
  api/meta_docs/README.md
  documentation/conf.py
  documentation/guides/api/develop.md
  documentation/guides/api/index.md
  documentation/guides/api/test.md
  documentation/guides/frontend/develop.md
  documentation/guides/frontend/index.md
  documentation/guides/frontend/test.md
  documentation/guides/general_setup.md
  documentation/guides/index.md
  documentation/guides/ingestion_server/develop.md
  documentation/guides/ingestion_server/index.md
  documentation/guides/ingestion_server/test.md
  documentation/guides/quickstart.md
  documentation/index.md
  documentation/justfile
  documentation/reference/dev_flow.md
  documentation/reference/github_contribution_practices.md
  documentation/reference/index.md
  frontend/meta_docs/CONTRIBUTING.md
  frontend/meta_docs/README.md
  ingestion_server/justfile
  justfile
Labels: 🟨 priority: medium, 🌟 goal: addition, 📄 aspect: text

#773 Prevent injection in weekly report script
  .github/workflows/weekly_updates.yml
  automations/js/justfile
  automations/js/package.json
  automations/js/src/html.mjs
  automations/js/src/last_week_tonight.mjs
  automations/js/src/weekly_report.js
  pnpm-lock.yaml
Labels: 🟨 priority: medium, ✨ goal: improvement, 💻 aspect: code

#780 Use Axios instead of node-fetch
  .github/filters.yml
  automations/js/package.json
  automations/js/src/last_week_tonight.mjs
  frontend/Dockerfile.playwright
  frontend/bin/playwright.sh
  frontend/docker-compose.playwright.yml
  frontend/package.json
  pnpm-lock.yaml
Labels: 🟥 priority: critical, 🛠 goal: fix, 💻 aspect: code, 🧱 stack: mgmt

#784 Exclude monorepo-specific issue templates from sync
  .github/sync.yml
Labels: 🟧 priority: high, 🛠 goal: fix, 🤖 aspect: dx, 🧱 stack: mgmt

#758 Update issues link on the about page
  frontend/src/pages/about.vue
Labels: 🟩 priority: low, ✨ goal: improvement, 📄 aspect: text

#797 Mark jpg images and fonts as binary files
  .gitattributes
  .github/ISSUE_TEMPLATE/design_changes.md
Labels: 🟨 priority: medium, 🛠 goal: fix, 💻 aspect: code, 🧱 stack: mgmt

#799 Fix incorrect path for Playwright test results
  .github/filters.yml
  .github/workflows/ci_cd.yml
Labels: 🟧 priority: high, 🛠 goal: fix, 🤖 aspect: dx

#767 Unify rollback & deployment, simplify deployment workflow
  .github/actions/production-nuxt-deploy/action.yml
  .github/actions/staging-api-deploy/action.yml
  .github/actions/staging-nuxt-deploy/action.yml
  .github/workflows/ci_cd.yml
  .github/workflows/deployment.yml
  .github/workflows/rollback.yml
Labels: 🟧 priority: high, 🛠 goal: fix, 🤖 aspect: dx, 🧱 stack: api, 🧱 stack: frontend
