Repository WordPress/openverse, pull requests merged in 2023-01, with the labels that each got.

#356 Render per-repo pull request template
  .github/sync.yml
  .pre-commit-config.local.yaml.jinja
  .pre-commit-config.yaml
  README.md
  justfile
  templates/.pre-commit-config.frontend.yaml.jinja
  templates/.pre-commit-config.local.yaml.jinja
  templates/.pre-commit-config.yaml.jinja
  templates/PULL_REQUEST_TEMPLATE.catalog.md.jinja
  templates/PULL_REQUEST_TEMPLATE.md.jinja
  templates/prettier.config.frontend.js.jinja
  templates/prettier.config.js.jinja
Labels: 🟩 priority: low, 🤖 aspect: dx, 🧰 goal: internal improvement

#359 Run label check on every commit and label change
  .github/workflows/pr_label_check.yml
Labels: 🟨 priority: medium, 🛠 goal: fix, 🤖 aspect: dx, 🤯 ノಠ益ಠノ彡┻━┻

#363 Add pydocstyle and guide for editing templates
  .pre-commit-config.yaml
  automations/python/issues_with_prs.py
  automations/python/label_pr.py
  automations/python/models/label.py
  automations/python/models/label_group.py
  automations/python/shared/data.py
  automations/python/shared/github.py
  automations/python/shared/log.py
  automations/python/sync_labels.py
  dead_links/dead_link_tally.py
  justfile
  templates/.pre-commit-config.yaml.jinja
  templates/README.md
Labels: 🟩 priority: low, 💻 aspect: code, 🧰 goal: internal improvement

#365 Don't run pre-commit on retired files
  .pre-commit-config.yaml
  templates/.pre-commit-config.yaml.jinja
Labels: 🟨 priority: medium, 🛠 goal: fix, 🤖 aspect: dx

#312 RFC: Frontend event tracking
  rfcs/20221006-frontend_event_tracking.md
Labels: 🟨 priority: medium, ✨ goal: improvement, 💻 aspect: code

#367 Update `isort` to fix problems with Poetry
  .github/workflows/lint.yml
  .pre-commit-config.yaml
  templates/.pre-commit-config.yaml.jinja
Labels: 🟧 priority: high, 🛠 goal: fix, 💻 aspect: code
